In [1]:
import pickle as pkl

In [2]:
file = open('model.pkl','rb')
model = pkl.load(file)
file.close()

In [3]:
file = open('gender_label.pkl','rb')
gender_label = pkl.load(file)
file.close()

file = open('gender_onehot.pkl','rb')
gender_onehot = pkl.load(file)
file.close()

file = open('severity_label.pkl','rb')
severity_label = pkl.load(file)
file.close()

file = open('severity_onehot.pkl','rb')
severity_onehot = pkl.load(file)
file.close()

file = open('contact_label.pkl','rb')
contact_label = pkl.load(file)
file.close()

file = open('contact_onehot.pkl','rb')
contact_onehot = pkl.load(file)
file.close()

file = open('minmax.pkl','rb')
minmax = pkl.load(file)
file.close()

In [4]:
age = 50
gender = 'Male'
fever = 99
bodypain = 1
runny_nose = 0 
diff = 0
nasal =1
sore_throat = 0
severity = 'Mild'
contact = 'no'

In [5]:
gender = gender_onehot.transform([gender_label.transform([gender])]).toarray()

In [6]:
severity = severity_onehot.transform([severity_label.transform([severity])]).toarray()

In [7]:
contact = contact_onehot.transform([contact_label.transform([contact])]).toarray()

In [8]:
gender

array([[0., 1., 0.]])

In [9]:
severity

array([[1., 0., 0.]])

In [10]:
contact

array([[1., 0., 0.]])

In [11]:
import numpy as np

In [12]:
test_data = np.array([[age,fever,bodypain,runny_nose,diff,nasal,sore_throat]])

In [13]:
test_data

array([[50, 99,  1,  0,  0,  1,  0]])

In [14]:
test_X = np.c_[test_data,gender,severity,contact]

In [15]:
test_X

array([[50., 99.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
         1.,  0.,  0.]])

In [16]:
test_X = minmax.transform(test_X)

In [17]:
test_X

array([[0.50632911, 0.16666667, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ]])

In [18]:
model.predict(test_X)

array([0], dtype=int64)